import email
from email.policy import default
from ssl import VerifyFlags
from tkinter import TRUE
from urllib import request
from django.db import models
from django.forms import CharField

# Create your models here.
    
class UserMaster(models.Model):
    email = models.EmailField( max_length=254)
    password = models.CharField( max_length=50)
    otp = models.IntegerField()
    role = models.CharField( max_length=50)
    is_active = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    is_created = models.DateTimeField( auto_now_add=True)
    is_updated = models.DateTimeField( auto_now_add=True)
    def __str__(self):
        return "%s %s " % (self.email,self.role)  
    
    
class Candidate(models.Model):
    user_id = models.ForeignKey(UserMaster, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    firstname = models.CharField( max_length=50)
    middlename = models.CharField(max_length=200)
    lastname = models.CharField( max_length=50)
    designation = models.CharField(max_length=50 , default='')
    dob = models.CharField( max_length=50)
    gender = models.CharField( max_length=50)
    marital_status = models.CharField(max_length=200)
    linkden = models.CharField(max_length=200)
    website = models.CharField(max_length=50)
    contact = models.CharField( max_length=50)
    city = models.CharField( max_length=50)
    state = models.CharField( max_length=50)
    country = models.CharField( max_length=50 , default='')
    pincode = models.CharField(max_length=50, default='')
    address = models.CharField( max_length=150)
    qualification1 = models.CharField(max_length=200)
    degree1 = models.CharField(max_length=200)
    college1 = models.CharField(max_length=200)
    CGPA1 = models.CharField( max_length=50 ,default='')
    datefrom1 = models.CharField(max_length=200)
    dateto1 = models.CharField(max_length=200)
    qualification2 = models.CharField(max_length=200)
    degree2 = models.CharField(max_length=200)
    college2 = models.CharField(max_length=200)
    CGPA2 = models.CharField( max_length=50 ,default='')
    datefrom2 = models.CharField(max_length=200)
    dateto2 = models.CharField(max_length=200)
    qualification3 = models.CharField(max_length=200)
    degree3 = models.CharField(max_length=200)
    college3 = models.CharField(max_length=200)
    CGPA3 = models.CharField( max_length=50 ,default='')
    datefrom3 = models.CharField(max_length=200)
    dateto3 = models.CharField(max_length=200)
    experience = models.CharField( max_length=50)
    companyname1 = models.CharField(max_length=200)
    companywebsite1 =models.CharField( max_length=250)
    jobposition1= models.CharField(max_length=200)
    c_city1 = models.CharField(max_length=200)
    cwh1 = models.CharField(max_length=20)
    date_from1 = models.CharField(max_length=200)
    date_to1 = models.CharField(max_length=200)
    addinfo1 = models.TextField(max_length=5000)
    companyname2 = models.CharField(max_length=200)
    companywebsite2 =models.CharField( max_length=250)
    jobposition2 = models.CharField(max_length=200)
    c_city2 = models.CharField(max_length=200)
    cwh2 = models.CharField(max_length=20)
    date_from2 = models.CharField(max_length=200)
    date_to2 = models.CharField(max_length=200)
    addinfo2 = models.TextField(max_length=5000)
    companyname3 = models.CharField(max_length=200)
    companywebsite3 =models.CharField( max_length=250)
    jobposition3 = models.CharField(max_length=200)
    c_city3 = models.CharField(max_length=200)
    cwh3 = models.CharField(max_length=20)
    date_from3 = models.CharField(max_length=200)
    date_to3 = models.CharField(max_length=200)
    addinfo3 = models.TextField(max_length=5000)
    skills= models.TextField(max_length=1000)
    c_ctc = models.BigIntegerField(default=0)
    e_ctc = models.BigIntegerField(default=0)
    objective = models.TextField( max_length=2000)
    profilepic = models.ImageField( upload_to='app/img/candidate')
    upload_resume = models.FileField( upload_to='app/resume/candidate')
    def __str__(self) :
        return "%s %s %s"%(self.firstname,self.lastname,self.profilepic)
    
class Company(models.Model):
    user_id = models.ForeignKey(UserMaster, on_delete=models.CASCADE)
    is_verified = models.BooleanField(default=False)
    established_on = models.CharField(max_length=50)
    services = models.TextField(max_length=2000)
    employee =models.IntegerField()
    average_ctc = models.CharField( max_length=100)
    firstname = models.CharField( max_length=50)
    lastname = models.CharField( max_length=50)
    company_name = models.CharField( max_length=50)
    company_email = models.CharField( max_length=200)
    contact = models.CharField( max_length=50)
    city = models.CharField( max_length=50)
    state = models.CharField( max_length=50)
    website = models.CharField(max_length=50)
    country = models.CharField( max_length=50)
    address = models.CharField( max_length=150)
    description = models.CharField( max_length=1500)    
    logo_pic = models.ImageField( upload_to='app/img/company')
    def __str__(self) :
        return "%s %s %s"%(self.firstname,self.lastname,self.logo_pic)
    

class Jobdetails(models.Model):
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    companyname = models.CharField( max_length=250)
    companyemail = models.CharField( max_length=200)
    companycontact = models.CharField( max_length=100)
    companywebsite = models.CharField(max_length=200)
    companyaddress = models.CharField( max_length=350)
    companydescription =models.CharField( max_length=5000)
    jobname = models.CharField( max_length=250)   
    jobtype = models.CharField(max_length=50)
    jobcategory = models.CharField(max_length=250)
    location = models.CharField( max_length=250)
    jobdescription = models.TextField( max_length=2500)
    responsibilities = models.TextField( max_length=5000) 
    date_posted = models.DateTimeField( auto_now=False, auto_now_add=TRUE)
    skills = models.CharField( max_length=500) 
    qualification = models.CharField( max_length=250)   
    salarypackage = models.CharField( max_length=100)
    experience= models.CharField(max_length=50,default="") 
    doca = models.CharField( max_length=50, default="")
    shift = models.CharField(max_length=250)
    gender = models.CharField(max_length=250)
    Image = models.ImageField( upload_to='app/image/logo',default="")
    
    def __str__(self) :
        return "%s %s %s %s"%(self.jobname,self.companyname,self.salarypackage, self.experience)
    
class Jobapply(models.Model):
    candidate = models.ForeignKey(Candidate,on_delete=models.CASCADE)
    job = models.ForeignKey(Jobdetails , on_delete=models.CASCADE)
    jobtitle = models.CharField( max_length=200 , default="")
    country = models.CharField(max_length=250)
    firstname = models.CharField(max_length=200)
    middlename = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    dob= models.CharField(max_length=200)
    gender = models.CharField(max_length=200)
    marital_status = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    linkden = models.CharField(max_length=200)
    website= models.CharField(max_length=200)
    address = models.CharField(max_length=500)
    qualification1 = models.CharField(max_length=200)
    degree1 = models.CharField(max_length=200)
    college1 = models.CharField(max_length=200)
    CGPA1 = models.CharField( max_length=50 ,default='')
    datefrom1 = models.CharField(max_length=200)
    dateto1 = models.CharField(max_length=200)
    qualification2 = models.CharField(max_length=200)
    degree2 = models.CharField(max_length=200)
    college2 = models.CharField(max_length=200)
    CGPA2 = models.CharField( max_length=50 ,default='')
    datefrom2 = models.CharField(max_length=200)
    dateto2 = models.CharField(max_length=200)
    qualification3 = models.CharField(max_length=200)
    degree3 = models.CharField(max_length=200)
    college3 = models.CharField(max_length=200)
    CGPA3 = models.CharField( max_length=50 ,default='')
    datefrom3 = models.CharField(max_length=200)
    dateto3 = models.CharField(max_length=200)
    experience = models.CharField(max_length=50)
    companyname1 = models.CharField(max_length=200)
    jobposiion1= models.CharField(max_length=200)
    c_city1 = models.CharField(max_length=200)
    cwh1 = models.CharField(max_length=20)
    date_from1 = models.CharField(max_length=200)
    date_to1 = models.CharField(max_length=200)
    addinfo1 = models.TextField(max_length=5000)
    companyname2 = models.CharField(max_length=200)
    jobposiion2 = models.CharField(max_length=200)
    c_city2 = models.CharField(max_length=200)
    cwh2 = models.CharField(max_length=20)
    date_from2 = models.CharField(max_length=200)
    date_to2 = models.CharField(max_length=200)
    addinfo2 = models.TextField(max_length=5000)
    companyname3 = models.CharField(max_length=200)
    jobposiion3 = models.CharField(max_length=200)
    c_city3 = models.CharField(max_length=200)
    cwh3 = models.CharField(max_length=20)
    date_from3 = models.CharField(max_length=200)
    date_to3 = models.CharField(max_length=200)
    addinfo3 = models.TextField(max_length=5000)
    skills= models.TextField(max_length=1000)
    resume= models.FileField( upload_to="app/candidate/resume", max_length=100)
    c_ctc = models.BigIntegerField(default=0)
    e_ctc = models.BigIntegerField(default=0)
    
    def __str__(self):
        return "%s %s "%(self.firstname,self.jobtitle)
    
class Adminlogin(models.Model):
    username = models.CharField( max_length=50)
    password = models.CharField( max_length=50)
    
    def __str__(self):
        return "%s "% (self.username,)

    

class Subscribtion(models.Manager):
    s_email = models.EmailField( max_length=254)
    
    def __str__(self):
        return "%s "% (self.s_email,)

    

    