# Generated by Django 4.1 on 2022-08-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
                ('logo_pic', models.ImageField(upload_to='app/img/company')),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=250)),
                ('companyemail', models.CharField(max_length=200)),
                ('companycontact', models.CharField(max_length=100)),
                ('companywebsite', models.CharField(max_length=200)),
                ('companyaddress', models.CharField(max_length=350)),
                ('jobname', models.CharField(max_length=250)),
                ('jobtype', models.CharField(max_length=50)),
                ('jobcategory', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('jobdescription', models.TextField(max_length=2500)),
                ('responsibilities', models.TextField(max_length=5000)),
                ('qualification', models.CharField(max_length=250)),
                ('salarypackage', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('doca', models.CharField(default='', max_length=50)),
                ('shift', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('c_ctc', models.BigIntegerField(default=0)),
                ('e_ctc', models.BigIntegerField(default=0)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('objective', models.CharField(max_length=1000)),
                ('profile_pic', models.ImageField(upload_to='app/img/candidate')),
                ('upload_resume', models.FileField(upload_to='app/resume/candidate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
    ]
