# Generated by Django 4.1 on 2022-08-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_jobdetails_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='logo_pic',
            field=models.ImageField(default='', upload_to='app/img/company'),
            preserve_default=False,
        ),
    ]
