# Generated by Django 4.1 on 2022-08-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobdetails_logo_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='logo_pic',
            new_name='logo',
        ),
    ]
