# Generated by Django 4.1 on 2022-08-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_logo_pic_jobdetails_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default='', upload_to='app/img/jobpost'),
        ),
    ]
