# Generated by Django 4.1 on 2022-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_jobdetails_logo_jobdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='Image',
            field=models.ImageField(default='', upload_to='app/image/logo'),
        ),
    ]
