# Generated by Django 4.1 on 2022-08-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_additional_info_jobapply_addinfo1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapply',
            old_name='marital_staus',
            new_name='marital_status',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='experience',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapply',
            name='jobtitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
