# Generated by Django 4.1 on 2022-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_marital_staus_jobapply_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='CGPA1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='CGPA2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='CGPA3',
            field=models.CharField(default='', max_length=50),
        ),
    ]
