# Generated by Django 4.1 on 2022-08-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_jobapply_cgpa1_jobapply_cgpa2_jobapply_cgpa3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='c_ctc',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='e_ctc',
            field=models.BigIntegerField(default=0),
        ),
    ]
