# Generated by Django 4.1 on 2022-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_adminlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
