# Generated by Django 4.1 on 2022-08-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_candidate_education_candidate_cgpa1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pincode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
