# Generated by Django 4.1 on 2022-09-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_candidate_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='jobposiion1',
            new_name='jobposition1',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='jobposiion2',
            new_name='jobposition2',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='jobposiion3',
            new_name='jobposition3',
        ),
    ]
