# Generated by Django 4.1 on 2022-09-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_jobposiion1_candidate_jobposition1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='profile_pic',
            new_name='profilepic',
        ),
    ]
