# Generated by Django 4.1 on 2022-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_candidate_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='companywebsite1',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='companywebsite2',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='companywebsite3',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='objective',
            field=models.TextField(max_length=2000),
        ),
    ]
