# Generated by Django 4.1 on 2022-09-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_candidate_companywebsite1_candidate_companywebsite2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
            preserve_default=False,
        ),
    ]
