# Generated by Django 4.1 on 2022-09-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_jobdetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='skills',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
