# Generated by Django 4.1 on 2022-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_jobdetails_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='companydescription',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
