# Generated by Django 4.1 on 2022-09-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_jobdetails_companydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
