# Generated by Django 4.1 on 2022-09-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_jobdetails_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
