# Generated by Django 4.1 on 2022-09-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_jobdetails_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='employee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='established_on',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
