# Generated by Django 4.1 on 2022-09-06 16:25

from django.db import migrations, models
import ssl


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_company_company_email_company_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='average_ctc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=ssl.VerifyFlags),
        ),
    ]
