# Generated by Django 4.1 on 2022-09-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_company_average_ctc_alter_company_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
